### PR TITLE
concrete framed blocks support

### PR DESCRIPTION
**Pull request by Flakxo**
partial support for framed blocks, concrete only

### CODE REVIEW

**Comment by XFactHD** [comment]
To what degree was this tested before being merged? Since the blocks added by FramedBlocks can take the appearance of almost any other full block, adding the material specifications of a specific block to all framed blocks means that any block applied to the framed block will take those material properties instead of its own (or none as is currently the case due to technical limitations).

As an example, the first image is Complementary Reimagined with Euphoria patches as packaged in whatever version of ATM10 I currently have and the second image is the same shader pack but with the latest `block.properties` file after this PR (neither oak logs nor stone blocks are supposed to be that shiny):

**Comment by SpacEagle17** [comment]
Are those normal oak blocks or the ones from frameblocks?
Thanks for your comment :)

**Comment by XFactHD** [comment]
Thank you. While this resolves the primary issue, it still has adverse effects on a few blocks, in particular breaking emission on the torches and significantly darkening the shading on horizontally angled faces. It would probably be best to not add the blocks at all, especially considering that I have plans for proper shader interop in the future.

**Comment by SpacEagle17** [comment]
That's interesting...
I just added them to the no properties entry. It shouldn't be any different from not adding them at all except that they are internally now registered as non-full blocks which makes them work correctly with ACL. Nothing should have changed visually hm

**Pull request merged**
